apiVersion: v1
kind: Service
metadata:
  name: api-golang
  namespace: system-tester
spec:
#  type: NodePort
  selector:
    app: api-golang
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
#      nodePort: 32081

