apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrator
  namespace: system-tester
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: superelectron/kubernetes-postgres-migration:latest
          args:
            - -path=/app/migrations
            - -database=$(DATABASE_URL)?sslmode=disable
            - up
          envFrom:
            - secretRef:
                name: db-password
      restartPolicy: OnFailure
