database:
  host: postgres-postgresql.postgres.svc.cluster.local

secret:
  name: db-password
  postgresPassword: foobarbaz

migrator:
  image: bitnami/postgresql:latest

migrationConfigMap: db-migration-scripts


primary:
  resources:
    limits:
      ephemeral-storage: 1Gi
      memory: 500Mi
    requests:
      cpu: 100m
      ephemeral-storage: 50Mi
      memory: 128Mi
