version: "3"

vars:
  IMAGE_REPO: superelectron/kubernetes-postgres
  IMAGE_TAG: latest

tasks:

  build:
    desc: Build multi-arch container image
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .

  build-migration:
    desc: Build multi-arch container image for the database migration image
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -f ./migrations.Dockerfile \
        -t {{.IMAGE_REPO}}-migration:{{.IMAGE_TAG}} \
        --push \
        .