apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoint }}
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.path }}`)
      services:
        - kind: Service
          name: {{ .Release.Name }}
          port: {{ .Values.service.port }}
          scheme: http
      middlewares:
        - name: {{ .Values.ingress.middleware }}
