version: "3"

vars:
  IMAGE_REPO: superelectron/kubernetes-react-nginx
  IMAGE_TAG: latest

tasks:

  build:
    desc: Build multi-arch container image
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .
