# 🚨 This is currently unused (for example purposes)
# The env var is defined directly in the deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: load-generator-config
  namespace: system-tester
data:
  API_URL: http://api-golang.system-tester.svc.cluster.local:8080
  DELAY_MS: "100"
