apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: system-tester
  labels:
    app: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
        - name: load-generator
          image: superelectron/kubernetes-load-generator:latest
          imagePullPolicy: Always
          env:
            - name: API_URL
              value: http://subnet.mysite.com/api/golang
            - name: DELAY_MS
              value: "500"
          # Could alternatively move these to a configmap
          # envFrom:
          #   - configMapRef:
          #       name: load-generator-config
          resources:
            limits:
              memory: "50Mi"
            requests:
              memory: "50Mi"
              cpu: "100m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      imagePullSecrets:
        - name: dockerconfigjson
      securityContext:
        seccompProfile:
          type: RuntimeDefault
